In [3]:
import pandas as pd
import numpy as np

In [4]:
import pandas as pd
df = pd.read_csv("students_data_2000_rows.csv")
df.head(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
0,1001,Student_1,19,Male,ECE,Chandigarh,63,68
1,1002,Student_2,19,Male,CE,Amritsar,39,61
2,1003,Student_3,19,Male,IT,Jaipur,38,95
3,1004,Student_4,21,Female,IT,Amritsar,70,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54,73
5,1006,Student_6,23,Male,CSE,Amritsar,47,82
6,1007,Student_7,23,Female,CSE,Amritsar,50,84
7,1008,Student_8,19,Female,CE,Ludhiana,59,64
8,1009,Student_9,18,Male,ECE,Delhi,64,66
9,1010,Student_10,24,Female,ME,Ludhiana,55,83

In [5]:

df.tail(10)                          # Last 10 rows

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1990,2991,Student_1991,19,Male,ME,Delhi,83,68
1991,2992,Student_1992,18,Male,CE,Delhi,56,72
1992,2993,Student_1993,25,Male,CSE,Amritsar,98,70
1993,2994,Student_1994,25,Male,CE,Amritsar,86,60
1994,2995,Student_1995,22,Male,ME,Ludhiana,69,93
1995,2996,Student_1996,23,Female,CE,Chandigarh,53,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59,72

In [6]:

df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'City', 'Marks',
       'Attendance'],
      dtype='object')

In [7]:

df.describe()

        Student_ID          Age        Marks   Attendance
count  2000.000000  2000.000000  2000.000000  2000.000000
mean   2000.500000    21.535000    67.355000    80.185000
std     577.494589     2.327764    18.928976    11.772811
min    1001.000000    18.000000    35.000000    60.000000
25%    1500.750000    19.000000    51.000000    70.000000
50%    2000.500000    22.000000    67.000000    80.000000
75%    2500.250000    24.000000    83.250000    91.000000
max    3000.000000    25.000000   100.000000   100.000000

In [8]:

df.rename(columns={"Name":"Student_Name"})

,Student_ID,Student_Name,Age,Gender,Department,City,Marks,Attendance
0,1001,Student_1,19,Male,ECE,Chandigarh,63,68
1,1002,Student_2,19,Male,CE,Amritsar,39,61
2,1003,Student_3,19,Male,IT,Jaipur,38,95
3,1004,Student_4,21,Female,IT,Amritsar,70,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54,73
...,...,...,...,...,...,...,...,...
1995,2996,Student_1996,23,Female,CE,Chandigarh,53,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59,72

In [10]:

df.drop("Age", axis=1)

,Student_ID,Name,Gender,Department,City,Marks,Attendance
0,1001,Student_1,Male,ECE,Chandigarh,63,68
1,1002,Student_2,Male,CE,Amritsar,39,61
2,1003,Student_3,Male,IT,Jaipur,38,95
3,1004,Student_4,Female,IT,Amritsar,70,60
4,1005,Student_5,Female,ECE,Ludhiana,54,73
...,...,...,...,...,...,...,...
1995,2996,Student_1996,Female,CE,Chandigarh,53,78
1996,2997,Student_1997,Female,CE,Jaipur,67,90
1997,2998,Student_1998,Male,ECE,Chandigarh,56,93
1998,2999,Student_1999,Male,ECE,Amritsar,57,69
1999,3000,Student_2000,Male,CSE,Ludhiana,59,72

In [11]:

df[["Name","Marks"]]

              Name  Marks
0        Student_1     63
1        Student_2     39
2        Student_3     38
3        Student_4     70
4        Student_5     54
...            ...    ...
1995  Student_1996     53
1996  Student_1997     67
1997  Student_1998     56
1998  Student_1999     57
1999  Student_2000     59

[2000 rows x 2 columns]

In [12]:
df.sort_values(by="Marks", ascending=True)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1814,2815,Student_1815,19,Male,ME,Ludhiana,35,87
914,1915,Student_915,20,Male,IT,Chandigarh,35,99
262,1263,Student_263,21,Male,ECE,Amritsar,35,99
29,1030,Student_30,18,Male,CE,Chandigarh,35,64
1063,2064,Student_1064,24,Male,CE,Chandigarh,35,86
...,...,...,...,...,...,...,...,...
1942,2943,Student_1943,22,Male,CSE,Chandigarh,100,70
1570,2571,Student_1571,24,Male,ME,Amritsar,100,94
1746,2747,Student_1747,22,Female,ME,Amritsar,100,85
1781,2782,Student_1782,21,Female,ME,Amritsar,100,72
304,1305,Student_305,23,Female,IT,Ludhiana,100,95

In [15]:

df.sample(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1077,2078,Student_1078,24,Female,CSE,Delhi,82,82
190,1191,Student_191,20,Female,IT,Delhi,38,68
751,1752,Student_752,22,Female,ME,Chandigarh,50,74
835,1836,Student_836,22,Female,ME,Delhi,99,84
388,1389,Student_389,21,Female,CE,Ludhiana,67,91
1231,2232,Student_1232,18,Male,ME,Delhi,66,91
150,1151,Student_151,22,Male,ECE,Ludhiana,97,69
1115,2116,Student_1116,18,Female,IT,Jaipur,42,69
1014,2015,Student_1015,23,Male,ECE,Ludhiana,57,88
804,1805,Student_805,25,Male,CSE,Amritsar,74,83