In [37]:
import pandas as pd
import numpy as np

In [38]:
import pandas as pd
df = pd.read_csv("students_data_2000_rows.csv")
df.head(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
0,1001,Student_1,19,Male,ECE,Chandigarh,NaN,68
1,1002,Student_2,19,Male,CE,Amritsar,NaN,61
2,1003,Student_3,19,Male,IT,Jaipur,38.0,95
3,1004,Student_4,21,Female,IT,Amritsar,70.0,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54.0,73
5,1006,Student_6,23,Male,CSE,Amritsar,47.0,82
6,1007,Student_7,23,Female,CSE,Amritsar,50.0,84
7,1008,Student_8,19,Female,CE,Ludhiana,59.0,64
8,1009,Student_9,18,Male,ECE,Delhi,64.0,66
9,1010,Student_10,24,Female,ME,Ludhiana,55.0,83

In [39]:

df.tail(10)                          # Last 10 rows

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1990,2991,Student_1991,19,Male,ME,Delhi,83.0,68
1991,2992,Student_1992,18,Male,CE,Delhi,56.0,72
1992,2993,Student_1993,25,Male,CSE,Amritsar,98.0,70
1993,2994,Student_1994,25,Male,CE,Amritsar,86.0,60
1994,2995,Student_1995,22,Male,ME,Ludhiana,69.0,93
1995,2996,Student_1996,23,Female,CE,Chandigarh,53.0,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67.0,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56.0,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57.0,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59.0,72

In [40]:

df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'City', 'Marks',
       'Attendance'],
      dtype='object')

In [41]:

df.describe()

        Student_ID          Age        Marks   Attendance
count  2000.000000  2000.000000  1995.000000  2000.000000
mean   2000.500000    21.535000    67.391980    80.185000
std     577.494589     2.327764    18.932195    11.772811
min    1001.000000    18.000000    35.000000    60.000000
25%    1500.750000    19.000000    51.000000    70.000000
50%    2000.500000    22.000000    67.000000    80.000000
75%    2500.250000    24.000000    84.000000    91.000000
max    3000.000000    25.000000   100.000000   100.000000

In [42]:

df.rename(columns={"Name":"Student_Name"})

,Student_ID,Student_Name,Age,Gender,Department,City,Marks,Attendance
0,1001,Student_1,19,Male,ECE,Chandigarh,NaN,68
1,1002,Student_2,19,Male,CE,Amritsar,NaN,61
2,1003,Student_3,19,Male,IT,Jaipur,38.0,95
3,1004,Student_4,21,Female,IT,Amritsar,70.0,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54.0,73
...,...,...,...,...,...,...,...,...
1995,2996,Student_1996,23,Female,CE,Chandigarh,53.0,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67.0,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56.0,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57.0,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59.0,72

In [43]:
df[df["Marks"]>80]

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
15,1016,Student_16,21,Female,CE,Amritsar,86.0,83
19,1020,Student_20,22,Female,CSE,Ludhiana,90.0,70
23,1024,Student_24,23,Female,CSE,Delhi,81.0,79
26,1027,Student_27,20,Female,CE,Jaipur,89.0,73
27,1028,Student_28,21,Female,ME,Ludhiana,91.0,93
...,...,...,...,...,...,...,...,...
1988,2989,Student_1989,24,Male,ECE,Chandigarh,97.0,94
1989,2990,Student_1990,25,Female,IT,Ludhiana,94.0,90
1990,2991,Student_1991,19,Male,ME,Delhi,83.0,68
1992,2993,Student_1993,25,Male,CSE,Amritsar,98.0,70
1993,2994,Student_1994,25,Male,CE,Amritsar,86.0,60

In [44]:

df.drop("Age", axis=1)

,Student_ID,Name,Gender,Department,City,Marks,Attendance
0,1001,Student_1,Male,ECE,Chandigarh,NaN,68
1,1002,Student_2,Male,CE,Amritsar,NaN,61
2,1003,Student_3,Male,IT,Jaipur,38.0,95
3,1004,Student_4,Female,IT,Amritsar,70.0,60
4,1005,Student_5,Female,ECE,Ludhiana,54.0,73
...,...,...,...,...,...,...,...
1995,2996,Student_1996,Female,CE,Chandigarh,53.0,78
1996,2997,Student_1997,Female,CE,Jaipur,67.0,90
1997,2998,Student_1998,Male,ECE,Chandigarh,56.0,93
1998,2999,Student_1999,Male,ECE,Amritsar,57.0,69
1999,3000,Student_2000,Male,CSE,Ludhiana,59.0,72

In [45]:

df[["Name","Marks"]]

              Name  Marks
0        Student_1    NaN
1        Student_2    NaN
2        Student_3   38.0
3        Student_4   70.0
4        Student_5   54.0
...            ...    ...
1995  Student_1996   53.0
1996  Student_1997   67.0
1997  Student_1998   56.0
1998  Student_1999   57.0
1999  Student_2000   59.0

[2000 rows x 2 columns]

In [46]:
df.sort_values(by="Marks", ascending=True)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
753,1754,Student_754,23,Male,IT,Amritsar,35.0,65
29,1030,Student_30,18,Male,CE,Chandigarh,35.0,64
914,1915,Student_915,20,Male,IT,Chandigarh,35.0,99
1741,2742,Student_1742,23,Female,ME,Jaipur,35.0,70
393,1394,Student_394,18,Female,ME,Delhi,35.0,94
...,...,...,...,...,...,...,...,...
0,1001,Student_1,19,Male,ECE,Chandigarh,NaN,68
1,1002,Student_2,19,Male,CE,Amritsar,NaN,61
51,1052,Student_52,22,Male,IT,Ludhiana,NaN,66
58,1059,Student_59,18,Female,IT,Chandigarh,NaN,82
62,1063,Student_63,21,Female,ECE,Ludhiana,NaN,74

In [47]:

df.sample(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1230,2231,Student_1231,20,Female,CE,Jaipur,62.0,97
498,1499,Student_499,20,Male,IT,Amritsar,79.0,93
1844,2845,Student_1845,25,Male,ECE,Chandigarh,94.0,89
758,1759,Student_759,18,Male,CE,Chandigarh,39.0,83
529,1530,Student_530,18,Male,IT,Amritsar,51.0,65
1200,2201,Student_1201,18,Male,IT,Amritsar,52.0,60
102,1103,Student_103,22,Male,CE,Delhi,79.0,94
520,1521,Student_521,21,Male,CE,Delhi,54.0,66
1785,2786,Student_1786,25,Female,ECE,Ludhiana,50.0,95
582,1583,Student_583,19,Male,CE,Delhi,71.0,94

In [48]:
df.sort_values(by="Marks", ascending=False).tail(10)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
54,1055,Student_55,19,Female,ECE,Delhi,35.0,81
1490,2491,Student_1491,22,Male,IT,Amritsar,35.0,66
39,1040,Student_40,24,Male,IT,Amritsar,35.0,84
914,1915,Student_915,20,Male,IT,Chandigarh,35.0,99
753,1754,Student_754,23,Male,IT,Amritsar,35.0,65
0,1001,Student_1,19,Male,ECE,Chandigarh,NaN,68
1,1002,Student_2,19,Male,CE,Amritsar,NaN,61
51,1052,Student_52,22,Male,IT,Ludhiana,NaN,66
58,1059,Student_59,18,Female,IT,Chandigarh,NaN,82
62,1063,Student_63,21,Female,ECE,Ludhiana,NaN,74

In [49]:
df.drop(0)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
1,1002,Student_2,19,Male,CE,Amritsar,NaN,61
2,1003,Student_3,19,Male,IT,Jaipur,38.0,95
3,1004,Student_4,21,Female,IT,Amritsar,70.0,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54.0,73
5,1006,Student_6,23,Male,CSE,Amritsar,47.0,82
...,...,...,...,...,...,...,...,...
1995,2996,Student_1996,23,Female,CE,Chandigarh,53.0,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67.0,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56.0,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57.0,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59.0,72

In [52]:
df.isnull().sum()
df.fillna(0)

,Student_ID,Name,Age,Gender,Department,City,Marks,Attendance
0,1001,Student_1,19,Male,ECE,Chandigarh,0.0,68
1,1002,Student_2,19,Male,CE,Amritsar,0.0,61
2,1003,Student_3,19,Male,IT,Jaipur,38.0,95
3,1004,Student_4,21,Female,IT,Amritsar,70.0,60
4,1005,Student_5,20,Female,ECE,Ludhiana,54.0,73
...,...,...,...,...,...,...,...,...
1995,2996,Student_1996,23,Female,CE,Chandigarh,53.0,78
1996,2997,Student_1997,21,Female,CE,Jaipur,67.0,90
1997,2998,Student_1998,25,Male,ECE,Chandigarh,56.0,93
1998,2999,Student_1999,25,Male,ECE,Amritsar,57.0,69
1999,3000,Student_2000,25,Male,CSE,Ludhiana,59.0,72

In [53]:
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
Department    0
City          0
Marks         5
Attendance    0
dtype: int64

In [51]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [ ]:
import pandas as pd
import numpy as np

# Load the dataset
file_path = 'students_data_2000_rows.csv'
df = pd.read_csv(file_path)

# 1. Students with more than 85 marks, grouped by city
students_above_85 = df[df['Marks'] > 85]
students_above_85_by_city = students_above_85.groupby('City').size().reset_index(name='student_count')

# 2. CSE students sorted by attendance
cse_students_by_attendance = df[df['Department'] == 'CSE'].sort_values('Attendance', ascending=False)

# 3. Students with age greater than 20 and less than 25
age_filter = df[(df['Age'] > 20) & (df['Age'] < 25)]

# 4. Add a new column 'Fees' with random paid/pending values
np.random.seed(42)
df['Fees'] = np.random.choice(['paid', 'pending'], size=len(df))

# 5. Add a new column 'Result' based on marks
conditions = [
    df['Marks'] > 90,
    (df['Marks'] >= 80) & (df['Marks'] <= 90),
    (df['Marks'] >= 70) & (df['Marks'] < 80)
]
choices = ['A grade', 'B grade', 'C grade']
df['Result'] = np.select(conditions, choices, default='P grade')

# 6. Group by Gender and Department, showing average attendance per department
avg_attendance_by_gender_department = df.groupby(['Gender', 'Department'])['Attendance'].mean().reset_index()

# Display results
print('1) Students with marks > 85 grouped by city:')
print(students_above_85_by_city.to_string(index=False))
print('\n2) CSE students by attendance:')
print(cse_students_by_attendance[['Name', 'Attendance']].to_string(index=False))
print('\n3) Students aged between 21 and 24:')
print(age_filter[['Name', 'Age', 'Department', 'City', 'Marks']].to_string(index=False))
print('\n4) DataFrame with Fees column:')
print(df[['Name', 'Fees']].head().to_string(index=False))
print('\n5) Result column preview:')
print(df[['Name', 'Marks', 'Result']].head().to_string(index=False))
print('\n6) Average attendance by gender and department:')
print(avg_attendance_by_gender_department.to_string(index=False))